= Notes

=== Staff

- 6 Administrative
- 40 Drivers
- 6 Maintenance Staff
- 8 Cleaning Staff

Potentially more part time staff to support cleaning service

- 4 Staff
- 1 Manager
- 1 Assistant Manager

=== Vans

- 30 Vans
- -> 8 Small vans ( minor removal situations )
- -> 1 Small van ( items that require special care )
- -> 12 Medium sized vans ( smaller properties, apartments, 1-2 bedroom houses )
- -> 10 Larges vans ( 4 or more bedroom houses ) ( Sometimes 2 or more vans needed )

BILLING INFORMATION

The vans are charged out in a similar way with a flat rate based on van type, plus cost of mileage

Small vans will have a driver to move the items.
If heavy appliance then an assitant will accompany.

Medium vans will have a driver + 2 assistants.

Large vans will have driver + 3 assistants.

Prices can be negotiated.
Applies to:
- Clearance of properties until inspection
- Any electrical work ( removing lighting + reinstalling )

----
Flat Rate + Van Type + Optional Driver Fee
----

=== House Removals

Cusomter enquiries regarding house removals -> phone or email

Many phone calls and emails go unanswered or delayed






